"""A module provides a function to complete a prompt with OpenAI's model."""
import os
import logging
from typing import Iterable

from openai import AsyncOpenAI
from openai.types.chat import ChatCompletionMessageParam

from src.config import ChatModel, configs
from src.services.llm_queue import QUEUE, BUSY_RU, BusyError


# Local llama.cpp server on 8080 (OpenAI-compatible). Adapts the ready
# OpenAI client to the local model by only changing base_url.
LLAMA_BASE_URL = os.getenv("LLAMA_BASE_URL", "http://localhost:8080/v1")
client = AsyncOpenAI(api_key=configs.OPENAI_TOKEN, base_url=LLAMA_BASE_URL)
logger: logging.Logger = logging.getLogger(__name__)


def _sanitize_roles(messages) -> list:
    """Collapse consecutive same-role and drop empties (llama.cpp strict 400).

    Send-time only; stored history untouched. Keeps the newest on collapse.
    Normalizes to plain dicts (valid ChatCompletionMessageParam).
    """
    cleaned: list = []
    for m in messages or []:
        if isinstance(m, dict):
            role, content = m.get("role"), m.get("content")
        else:
            role = getattr(m, "role", "user")
            role = role.value if hasattr(role, "value") else str(role)
            content = getattr(m, "content", "")
        if isinstance(content, list):
            cleaned.append({"role": role, "content": content})
            continue
        text = (content or "").strip()
        if not text:
            continue
        if (cleaned and cleaned[-1].get("role") == role
                and isinstance(cleaned[-1].get("content"), str)):
            cleaned[-1] = {"role": role, "content": content}
            continue
        cleaned.append({"role": role, "content": content})
    return cleaned


async def complete(
    messages: Iterable[ChatCompletionMessageParam], chat_model: ChatModel
) -> str:
    """Completes the given prompt using OpenAI's language model.

    Args:
        messages: A list of messages comprising the conversation so far.
        chat_model: Chat model to use for the completion.

    Returns:
        str: The completed text generated by the model.
    """
    cleaned = _sanitize_roles(messages)
    params = chat_model.get_openai_chat_params()
    try:
        for _ in range(2):  # one retry on empty output
            completion = await QUEUE.run(
                client.chat.completions.create,
                messages=cleaned, **params,
            )
            text = (completion.choices[0].message.content or "").strip()
            if text:
                return text
        return ("Не получилось сформулировать ответ, "
                "попробуй переформулировать вопрос.")
    except BusyError:
        return BUSY_RU
    except Exception as e:
        logger.exception(
            "Error while completion: %s. Messages: %s", e, messages
        )
        raise


async def text_to_speech(text: str, chat_model: ChatModel) -> bytes:
    """Gets text to translate and a chat model to use, returns audio bytes.

    Args:
        text: Text to turn into audio speech. Max len: 4096.
        chat_model: Chat model to use for the translation.

    Returns:
        Return audio file as bytes.
    """
    max_input_len = 4096
    text = text[:max_input_len]
    response = await client.audio.speech.create(
        **chat_model.get_openai_speech_params(), input=text
    )
    return response.read()


async def speech_to_text(file_path: str, delete_file: bool = True) -> str:
    """Gets audio file path and returns transcribed text.

    Args:
        file_path: The audio file path to transcribe, in one of these formats:
            flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, or webm.
        delete_file: Delete audio file after transcribition. Default: True.

    Returns:
        The transcription text of the audio file.
    """
    with open(file_path, "rb") as audio_file:
        transcript = await client.audio.transcriptions.create(
            model="whisper-1", file=audio_file
        )

    if delete_file:
        os.remove(file_path)

    logger.debug("Transcribed text: %s", transcript.text)
    return transcript.text


async def complete_with_image(
    text: str, image_b64: str, chat_model: ChatModel
) -> str:
    """Chat completion with an image (for vision-capable local models).

    Uses the OpenAI image message format; llama.cpp multimodal servers
    accept base64 data URLs. `model` param is ignored by llama.cpp
    (it serves the loaded model).
    """
    messages = [{
        "role": "user",
        "content": [
            {"type": "text", "text": text or "Describe this image."},
            {"type": "image_url",
             "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"}},
        ],
    }]
    try:
        for _ in range(2):
            completion = await QUEUE.run(
                client.chat.completions.create,
                messages=messages, **chat_model.get_openai_chat_params(),
            )
            text = (completion.choices[0].message.content or "").strip()
            if text:
                return text
        return "Не смог описать изображение."
    except BusyError:
        return BUSY_RU
    except Exception as e:
        logger.exception("Error while vision completion: %s", e)
        raise
